### PR TITLE
Split code lines with preg_split instead of explode

### PR DESCRIPTION
**Pull request by nickknissen**
This merge request will make tlint work on windows when files uses unix newlines.

Currently the base linter splits code on `PHP_EOL`. Which on Windows is set to `\r\n` and other systems it's set to `\n`.  
See [here](https://github.com/php/php-src/blob/67e0138c0dfd966624223911a0821f6c294ad1c6/main/php.h#L61-L78) for reference.

By using `explode(PHP_EOL, $code)` files with unix newline will not be split on windows.

### CODE REVIEW

**Comment by loganhenson** [comment]
@nickknissen Thanks for the PR! (I've updated it to merge into `develop`)

PHP_EOL can definitely be dropped at this point, but without a testing environment with windows support, I might lean towards going a little more explicit with line splitting while we are here.

What are your thoughts on implementing something like: https://github.com/vlucas/phpdotenv/blob/54d599d414f8cf3f6129e287acaf44b610486aa1/src/Loader.php#L158 (Probably as a method on `BaseLinter`), and replacing the other usages of `PHP_EOL` throughout the codebase?

**Comment by nickknissen** [comment]
Unfortunately Windows on Travis CI doesn't support php yet.

But i gladly take a stab at implementing a `readLinesFromFile` method on `BaseLinter` sometime this week.

**Comment by loganhenson** [comment]
Ah, too bad.

The only thing that might prohibit us from using the phpdotenv implementation is that the code is already loaded and passed to the linter in `BaseLinter`. Since this is the case I'm totally fine with your original implementation.

I also don't want to hold this up if it is all it takes to fix TLint running on windows. Do any of the other locations that use the constant in the code cause errors in windows? (I believe they are formatting output and tests)

**Comment by nickknissen** [comment]
Using phpdotenv implementation would require lot of tests to be refactored because the `BaseLinter` currently takes a string and not a file. So it would properly be better to use `preg_split` for now.

All unittests runs on windows when my fix is applied, and as you said the other usages of PHP_EOL are fine.

**Pull request merged**
