### PR TITLE
make ModelMethodOrder and ClassThingsOrder linters compatible

### LINKED ISSUE #165: ModelMethodOrder and ClassThingsOrder conflicting
The `ModelMethodOrder` linter dictates that the "boot" method should come last, but since the boot method is static, `ClassThingsOrder` dictates that it should go first.

When I put my "boot" method at the top of the file, I get the following message: 
```
! Model method order should be: relationships > scopes > accessors > mutators > booting > boot > booted > custom
```

When I put it at the bottom:
```
! Class "things" should be ordered trait use, public static property, protected static property, private static property, public constant, protected constant, private constant, public property, protected property, private property, constructor, public static method, protected static method, private static method, public method, protected method, private method, magic method
```

This has been happening since version 5.0.2.

### PR DESCRIPTION
**Pull request by Gummibeer**
fixes #165

### CODE REVIEW

**Comment by Gummibeer** [comment]
@adriaanzon if you provide mee your full Model class - without method body is okay - I will add it as a testcase too. 🙂

**Comment by adriaanzon** [comment]
@Gummibeer here you go:

```php
<?php

namespace App\Models;

use App\Modules\Phonetics\HasTranslatableSections;
use App\Modules\Sluggable\Sluggable;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Laravel\Nova\Actions\Actionable;
use Laravel\Scout\Searchable;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;

class Song extends Model implements HasMedia
{
    use Actionable;
    use HasTranslatableSections;
    use InteractsWithMedia;
    use Searchable;
    use Sluggable;

    protected $appends = ['slug', 'title_with_translation'];

    protected $guarded = [];

    protected $hidden = ['internal_note'];

    protected static function boot()
    {
    }

    public function culture(): BelongsTo
    {
    }

    public function tenants(): BelongsToMany
    {
    }

    public function sections(): HasMany
    {
    }

    public function scopeNotOnCurrentTenant(Builder $query): void
    {
    }

    public function scopePublished(Builder $query): void
    {
    }

    public function getTitleWithTranslationAttribute()
    {
    }

    public function loadOrderedTranslatedSections(): self
    {
    }

    public function url(): string
    {
    }

    public function registerMediaCollections(): void
    {
    }

    public function toSearchableArray(): array
    {
    }

    public function shouldBeSearchable(): bool
    {
    }
}
```

**Comment by Gummibeer** [comment]
@adriaanzon thanks, have added your model and it passed the composite testcase. So your issue should be solved after this PR is merged. 🙂🎉

**Comment by loganhenson** [comment]
`v5.0.3` tagged

**Pull request merged**
